name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1) Get your code
      - uses: actions/checkout@v4

      # 2) Set up Python (pick the version you run locally)
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 3) Speed up installs by caching pip’s download dir
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # 4) Install your deps
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      # 5) Run tests (no real API calls; we still set dummy env vars your app expects)
      - name: Run tests
        env:
          OPENAI_API_KEY: test
          FLASK_ENV: testing
          SECRET_KEY: test
        run: pytest -q
